# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/MCL/python/succulentPlants/UI\UI_succulentPlants.ui'
#
# Created: Sun Jun 24 14:58:57 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1135, 677)
        Form.setStyleSheet(_fromUtf8(""))
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.treeView_type = QtGui.QTreeView(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_type.sizePolicy().hasHeightForWidth())
        self.treeView_type.setSizePolicy(sizePolicy)
        self.treeView_type.setMinimumSize(QtCore.QSize(260, 0))
        self.treeView_type.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.treeView_type.setFont(font)
        self.treeView_type.setObjectName(_fromUtf8("treeView_type"))
        self.horizontalLayout.addWidget(self.treeView_type)
        self.frame_2 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(520, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget_asset = QtGui.QWidget(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_asset.sizePolicy().hasHeightForWidth())
        self.widget_asset.setSizePolicy(sizePolicy)
        self.widget_asset.setObjectName(_fromUtf8("widget_asset"))
        self.verticalLayout_3.addWidget(self.widget_asset)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_message = QtGui.QWidget(self.frame_3)
        self.widget_message.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_message.sizePolicy().hasHeightForWidth())
        self.widget_message.setSizePolicy(sizePolicy)
        self.widget_message.setObjectName(_fromUtf8("widget_message"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_message)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_title = QtGui.QLabel(self.widget_message)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.verticalLayout_2.addWidget(self.label_title)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_From = QtGui.QLabel(self.widget_message)
        self.label_From.setObjectName(_fromUtf8("label_From"))
        self.gridLayout.addWidget(self.label_From, 5, 0, 1, 1)
        self.lineEdit_cName = QtGui.QLineEdit(self.widget_message)
        self.lineEdit_cName.setEnabled(False)
        self.lineEdit_cName.setFrame(False)
        self.lineEdit_cName.setObjectName(_fromUtf8("lineEdit_cName"))
        self.gridLayout.addWidget(self.lineEdit_cName, 0, 1, 1, 1)
        self.label_spell = QtGui.QLabel(self.widget_message)
        self.label_spell.setObjectName(_fromUtf8("label_spell"))
        self.gridLayout.addWidget(self.label_spell, 1, 0, 1, 1)
        self.lineEdit_From = QtGui.QLineEdit(self.widget_message)
        self.lineEdit_From.setFrame(False)
        self.lineEdit_From.setObjectName(_fromUtf8("lineEdit_From"))
        self.gridLayout.addWidget(self.lineEdit_From, 5, 1, 1, 1)
        self.lineEdit_lName = QtGui.QLineEdit(self.widget_message)
        self.lineEdit_lName.setFrame(False)
        self.lineEdit_lName.setObjectName(_fromUtf8("lineEdit_lName"))
        self.gridLayout.addWidget(self.lineEdit_lName, 3, 1, 1, 1)
        self.label_sOther = QtGui.QLabel(self.widget_message)
        self.label_sOther.setObjectName(_fromUtf8("label_sOther"))
        self.gridLayout.addWidget(self.label_sOther, 2, 0, 1, 1)
        self.lineEdit_spell = QtGui.QLineEdit(self.widget_message)
        self.lineEdit_spell.setEnabled(False)
        self.lineEdit_spell.setFrame(False)
        self.lineEdit_spell.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineEdit_spell.setReadOnly(False)
        self.lineEdit_spell.setObjectName(_fromUtf8("lineEdit_spell"))
        self.gridLayout.addWidget(self.lineEdit_spell, 1, 1, 1, 1)
        self.lineEdit_type = QtGui.QLineEdit(self.widget_message)
        self.lineEdit_type.setFrame(False)
        self.lineEdit_type.setObjectName(_fromUtf8("lineEdit_type"))
        self.gridLayout.addWidget(self.lineEdit_type, 4, 1, 1, 1)
        self.label_cName = QtGui.QLabel(self.widget_message)
        self.label_cName.setObjectName(_fromUtf8("label_cName"))
        self.gridLayout.addWidget(self.label_cName, 0, 0, 1, 1)
        self.label_type = QtGui.QLabel(self.widget_message)
        self.label_type.setObjectName(_fromUtf8("label_type"))
        self.gridLayout.addWidget(self.label_type, 4, 0, 1, 1)
        self.lineEdit_sOther = QtGui.QLineEdit(self.widget_message)
        self.lineEdit_sOther.setEnabled(False)
        self.lineEdit_sOther.setFrame(False)
        self.lineEdit_sOther.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineEdit_sOther.setReadOnly(False)
        self.lineEdit_sOther.setObjectName(_fromUtf8("lineEdit_sOther"))
        self.gridLayout.addWidget(self.lineEdit_sOther, 2, 1, 1, 1)
        self.label_lName = QtGui.QLabel(self.widget_message)
        self.label_lName.setObjectName(_fromUtf8("label_lName"))
        self.gridLayout.addWidget(self.label_lName, 3, 0, 1, 1)
        self.label_ID = QtGui.QLabel(self.widget_message)
        self.label_ID.setObjectName(_fromUtf8("label_ID"))
        self.gridLayout.addWidget(self.label_ID, 6, 0, 1, 1)
        self.lineEdit_ID = QtGui.QLineEdit(self.widget_message)
        self.lineEdit_ID.setFrame(False)
        self.lineEdit_ID.setObjectName(_fromUtf8("lineEdit_ID"))
        self.gridLayout.addWidget(self.lineEdit_ID, 6, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.textEdit_intro = QtGui.QTextEdit(self.widget_message)
        self.textEdit_intro.setObjectName(_fromUtf8("textEdit_intro"))
        self.verticalLayout_2.addWidget(self.textEdit_intro)
        self.verticalLayout.addWidget(self.widget_message)
        self.horizontalLayout.addWidget(self.frame_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_title.setText(_translate("Form", "标题", None))
        self.label_From.setText(_translate("Form", "产地分布 ：", None))
        self.label_spell.setText(_translate("Form", "拼音     ：", None))
        self.label_sOther.setText(_translate("Form", "别称     ：", None))
        self.label_cName.setText(_translate("Form", "中文名   ：", None))
        self.label_type.setText(_translate("Form", "科属     ：", None))
        self.label_lName.setText(_translate("Form", "拉丁学名 ：", None))
        self.label_ID.setText(_translate("Form", "ID       ：", None))

import succulentPlants_rc
